test_task:
  matrix:
    - container:
        image: rust:latest
    - container:
        image: rustlang/rust:nightly
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  env:
    matrix:
      - OA_FRONTEND: oxide-auth-actix
      - OA_FRONTEND: oxide-auth-iron
      - OA_FRONTEND: oxide-auth-rouille
  build_script: cargo build --no-default-features --features "$OA_FRONTEND"
  test_script: cargo test --no-default-features --features "$OA_FRONTEND"
  before_cache_script: rm -rf $CARGO_HOME/registry/index

nightly_task:
  container:
    image: rustlang/rust:nightly
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  pre_script: cargo --version
  build_script: cargo build --no-default-features --features "oxide-auth-rocket"
  test_script: cargo test --no-default-features --features "oxide-auth-rocket"
  before_cache_script: rm -rf $CARGO_HOME/registry/index

release_task:
  only_if: $CIRRUS_BRANCH =~ 'release.*'
  container:
    image: rust:latest
  script: ./release

doc_task:
  container:
    image: rustlang/rust:nightly
  script: cargo doc --no-deps --document-private-items --all-features
