test_stable_task:
  container:
    image: rust:latest
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  pre_script: cargo --version
  build_script: cargo build --all-features
  test_script: cargo test --all --exclude oxide-auth-rocket --exclude rocket-example
  before_cache_script: rm -rf $CARGO_HOME/registry/index
  
test_nightly_task:
  container:
    image: rustlang/rust:nightly
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  pre_script: cargo --version
  build_script: cargo build --all-features
  test_script: cargo test --all
  before_cache_script: rm -rf $CARGO_HOME/registry/index

release_task:
  only_if: $CIRRUS_BRANCH =~ 'release.*'
  container:
    image: rust:latest
  script: ./release

doc_task:
  container:
    image: rustlang/rust:nightly
  script: cargo doc --no-deps --document-private-items --all-features
