#!/bin/bash

# new version is last parameter
new_version="${!#}"

# check it is a sane version number
[[ -z $(grep -vE '[0-9a-zA-Z.-]*' <<< "$new_version" ) ]] || { echo "Fail: Check version number: ${new_version}"; exit 1; }

is_force=""

for param in $@
do
	case "$param" in
		-f) is_force="-f";;
	esac
done

# Check that the working dir is clean. May comment this out if it produces problems.
[[ -z $(git status -s) ]] || { echo "Fail: Working directory is not clean"; exit 1; }

# Check there are no more [WIP] markers in Migrate and Readme
[[ -z $(grep "WIP" Migration.md Readme.md) ]] || { echo "Fail: Work in progress in documentation"; exit 1; }

# Test that our version is actually the one in Cargo.toml
[[ -z $(grep "version = \"$new_version\"" Cargo.toml) ]] && { echo "Fail: Version differs from cargo version"; exit 1; }

# Packaging works. Note: does not publish the version.
cargo package || { echo "Fail: cargo could not package successfully"; exit 1; }

git tag -s "$is_force" "v$new_version"
